### ISSUE TITLE
Error in R4.3 + Julia 1.9.2 with Mac M1

### ISSUE THREAD

**Issue by gglee4ai** [SciML/diffeqr#41]
I've tried running JuliaCall and it works fine, but when I run diffeqr I get an error. 
I get the same error whether I install julia via brew on my Mac or diffeq_setup() from a clean install. 

```
de <- diffeqr::diffeq_setup()

f <- function(u,p,t) {
  return(1.01*u)
}

u0 <- 1/2
tspan <- c(0., 1.)

prob = de$ODEProblem(f, u0, tspan)
sol = de$solve(prob)
```

> Error: Error happens in Julia.
> type RFunction has no field r
> Stacktrace:
> [1] getproperty
> @ ./Base.jl:37 [inlined]
> [2] numargs(f::RCall.RFunction{RObject{ClosSxp}})
> @ SciMLBase ~/.julia/packages/SciMLBase/kTUaf/src/utils.jl:10
> [3] isinplace(f::RCall.RFunction{RObject{ClosSxp}}, inplace_param_number::Int64, fname::String, iip_preferred::Bool; has_two_dispatches::Bool, isoptimization::Bool)
> @ SciMLBase ~/.julia/packages/SciMLBase/kTUaf/src/utils.jl:242
> [4] isinplace(f::RCall.RFunction{RObject{ClosSxp}}, inplace_param_number::Int64, fname::String, iip_preferred::Bool)
> @ SciMLBase ~/.julia/packages/SciMLBase/kTUaf/src/utils.jl:240
> [5] isinplace(f::RCall.RFunction{RObject{ClosSxp}}, inplace_param_number::Int64)
> 
> @ SciMLBase ~/.julia/packages/SciMLBase/kTUaf/src/utils.jl:240
> [6] ODEProblem(f::RCall.RFunction{RObject{ClosSxp}}, u0::Float64, tspan::Vector{Float64}, p::SciMLBase.NullParameters; > kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
> @ SciMLB

**Comment by ChrisRackauckas** [comment]
What versions?

**Comment by gglee4ai** [comment]
System: MacOS 12.6.7 Monterey
R: 4.3.1 (from rig)
JuliaCall: 0.17.5 (installed from github dev version, because cran version causes error)
diffeqr: 1.1.3 (installed from github dev version)

**Comment by YoJimboDurant** [comment]
Same issue and error here with a windows install. R version 4.3 and Julia 1.9.3 and also tried Julia 1.6.7. Have tried CRAN and github installs.

**Comment by ChrisRackauckas** [comment]
This is fixed by https://github.com/SciML/SciMLBase.jl/pull/521. That patch should be released later today, so then as long as the Julia packages get updated this'll no longer error.

**Comment by FJRubio67** [comment]
Unfortunately, this did not solve the issue for me ( iMac with 12.6.8 MacOS Monterey, R 4.2.0, Julia 1.9). I re-installed all packages from GitHub and still got the same error.

> prob = de$ODEProblem(f, u0, tspan)
Error: Error happens in Julia.
type RFunction has no field r
Stacktrace:
 [1] getproperty
   @ ./Base.jl:37 [inlined]
 [2] numargs(f::RCall.RFunction{RObject{ClosSxp}})
   @ SciMLBase ~/.julia/packages/SciMLBase/Z5Cel/src/utils.jl:10
 [3] isinplace(f::RCall.RFunction{RObject{ClosSxp}}, inplace_param_number::Int64, fname::String, iip_preferred::Bool; has_two_dispatches::Bool, isoptimization::Bool)
   @ SciMLBase ~/.julia/packages/SciMLBase/Z5Cel/src/utils.jl:242
 [4] isinplace(f::RCall.RFunction{RObject{ClosSxp}}, inplace_param_number::Int64, fname::String, iip_preferred::Bool)
   @ SciMLBase ~/.julia/packages/SciMLBase/Z5Cel/src/utils.jl:240
 [5] isinplace(f::RCall.RFunction{RObject{ClosSxp}}, inplace_param_number::Int64)
   @ SciMLBase ~/.julia/packages/SciMLBase/Z5Cel/src/utils.jl:240
 [6] ODEProblem(f::RCall.RFunction{RObject{ClosSxp}}, u0::Float64, tspan::Vector{Float64}, p::SciMLBase.NullParameters; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ SciMLB

**Comment by ChrisRackauckas** [comment]
What version of SciMLBase?

**Comment by FJRubio67** [comment]
> What version of SciMLBase?

1.9.8. I guess that is the problem as I just ran Pkg.update("SciMLBase"), which installed this version. I will try to update it from GitHub. Many thanks for your help.

**Comment by ChrisRackauckas** [comment]
You need to make sure your registry is updated. The fix is in SciMLBase v2.3.1

**Comment by FJRubio67** [comment]
That solved the problem.  Thanks again.
